# Generated by Django 6.0 on 2025-12-28 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("日", "日給"), ("時", "時給"), ("件", "1件あたり")],
                        default="日",
                        max_length=10,
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(
                        choices=[
                            ("北海道", "北海道"),
                            ("青森県", "青森県"),
                            ("岩手県", "岩手県"),
                            ("宮城県", "宮城県"),
                            ("秋田県", "秋田県"),
                            ("山形県", "山形県"),
                            ("福島県", "福島県"),
                            ("茨城県", "茨城県"),
                            ("栃木県", "栃木県"),
                            ("群馬県", "群馬県"),
                            ("埼玉県", "埼玉県"),
                            ("千葉県", "千葉県"),
                            ("東京都", "東京都"),
                            ("神奈川県", "神奈川県"),
                            ("新潟県", "新潟県"),
                            ("富山県", "富山県"),
                            ("石川県", "石川県"),
                            ("福井県", "福井県"),
                            ("山梨県", "山梨県"),
                            ("長野県", "長野県"),
                            ("岐阜県", "岐阜県"),
                            ("静岡県", "静岡県"),
                            ("愛知県", "愛知県"),
                            ("三重県", "三重県"),
                            ("滋賀県", "滋賀県"),
                            ("京都府", "京都府"),
                            ("大阪府", "大阪府"),
                            ("兵庫県", "兵庫県"),
                            ("奈良県", "奈良県"),
                            ("和歌山県", "和歌山県"),
                            ("鳥取県", "鳥取県"),
                            ("島根県", "島根県"),
                            ("岡山県", "岡山県"),
                            ("広島県", "広島県"),
                            ("山口県", "山口県"),
                            ("徳島県", "徳島県"),
                            ("香川県", "香川県"),
                            ("愛媛県", "愛媛県"),
                            ("高知県", "高知県"),
                            ("福岡県", "福岡県"),
                            ("佐賀県", "佐賀県"),
                            ("長崎県", "長崎県"),
                            ("熊本県", "熊本県"),
                            ("大分県", "大分県"),
                            ("宮崎県", "宮崎県"),
                            ("鹿児島県", "鹿児島県"),
                            ("沖縄県", "沖縄県"),
                        ],
                        default="東京都",
                        max_length=10,
                        verbose_name="都道府県",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="", max_length=50, verbose_name="市区町村"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("headcount", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "選考中"),
                            ("accepted", "採用"),
                            ("rejected", "不採用"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="jobs.application",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
