# Generated by Django 6.0 on 2025-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="市区町村"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="募集期限"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(verbose_name="仕事内容の詳細"),
        ),
        migrations.AlterField(
            model_name="job",
            name="headcount",
            field=models.IntegerField(default=1, verbose_name="募集人数"),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="募集終了"),
        ),
        migrations.AlterField(
            model_name="job",
            name="price",
            field=models.IntegerField(verbose_name="金額"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=100, verbose_name="仕事のタイトル"),
        ),
        migrations.AlterField(
            model_name="job",
            name="unit",
            field=models.CharField(
                choices=[("日", "日給"), ("時", "時給"), ("件", "1件あたり")],
                default="日",
                max_length=10,
                verbose_name="単位",
            ),
        ),
    ]
