# Generated by Django 6.0 on 2025-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(default="applied", max_length=20),
        ),
        migrations.AddField(
            model_name="job",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
