# Generated by Django 6.0 on 2026-01-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_break_time_job_notes_job_qualifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="work_date",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="勤務日・期間"
            ),
        ),
    ]
