# Generated by Django 6.0 on 2025-12-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_application_status_job_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="募集期限"),
        ),
        migrations.AddField(
            model_name="job",
            name="headcount",
            field=models.IntegerField(default=1, verbose_name="募集人数"),
        ),
        migrations.AddField(
            model_name="job",
            name="unit",
            field=models.CharField(
                choices=[
                    ("日", "日給 (/日)"),
                    ("時", "時給 (/時間)"),
                    ("月", "月給 (/月)"),
                    ("一式", "一式 (請負)"),
                ],
                default="日",
                max_length=10,
                verbose_name="単位",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(verbose_name="仕事の詳細"),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="募集終了"),
        ),
        migrations.AlterField(
            model_name="job",
            name="price",
            field=models.IntegerField(verbose_name="金額"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=100, verbose_name="仕事のタイトル"),
        ),
    ]
