# Generated by Django 6.0 on 2026-02-02 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_message_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "多能工・手元"),
                    ("carpenter", "大工・造作"),
                    ("electric", "電気・通信"),
                    ("plumbing", "設備・水道"),
                    ("interior", "内装・クロス・床"),
                    ("exterior", "外装・塗装・防水"),
                    ("scaffold", "足場・鳶・土工"),
                    ("hvac", "空調・ダクト"),
                    ("cleaning", "クリーニング・雑工"),
                    ("other", "その他"),
                ],
                default="general",
                max_length=50,
                verbose_name="業種・職種",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="prefecture",
            field=models.CharField(
                choices=[
                    ("北海道", "北海道"),
                    ("青森県", "青森県"),
                    ("岩手県", "岩手県"),
                    ("宮城県", "宮城県"),
                    ("秋田県", "秋田県"),
                    ("山形県", "山形県"),
                    ("福島県", "福島県"),
                    ("茨城県", "茨城県"),
                    ("栃木県", "栃木県"),
                    ("群馬県", "群馬県"),
                    ("埼玉県", "埼玉県"),
                    ("千葉県", "千葉県"),
                    ("東京都", "東京都"),
                    ("神奈川県", "神奈川県"),
                    ("新潟県", "新潟県"),
                    ("富山県", "富山県"),
                    ("石川県", "石川県"),
                    ("福井県", "福井県"),
                    ("山梨県", "山梨県"),
                    ("長野県", "長野県"),
                    ("岐阜県", "岐阜県"),
                    ("静岡県", "静岡県"),
                    ("愛知県", "愛知県"),
                    ("三重県", "三重県"),
                    ("滋賀県", "滋賀県"),
                    ("大阪府", "大阪府"),
                    ("兵庫県", "兵庫県"),
                    ("奈良県", "奈良県"),
                    ("和歌山県", "和歌山県"),
                    ("鳥取県", "鳥取県"),
                    ("島根県", "島根県"),
                    ("岡山県", "岡山県"),
                    ("広島県", "広島県"),
                    ("山口県", "山口県"),
                    ("徳島県", "徳島県"),
                    ("香川県", "香川県"),
                    ("愛媛県", "愛媛県"),
                    ("高知県", "高知県"),
                    ("福岡県", "福岡県"),
                    ("佐賀県", "佐賀県"),
                    ("長崎県", "長崎県"),
                    ("熊本県", "熊本県"),
                    ("大分県", "大分県"),
                    ("宮崎県", "宮崎県"),
                    ("鹿児島県", "鹿児島県"),
                    ("沖縄県", "沖縄県"),
                ],
                default="徳島県",
                max_length=10,
                verbose_name="都道府県",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("employer_to_worker", "発注者からワーカーへ"),
                            ("worker_to_employer", "ワーカーから発注者へ"),
                        ],
                        max_length=20,
                        verbose_name="評価タイプ",
                    ),
                ),
                (
                    "ability",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="能力",
                    ),
                ),
                (
                    "cooperation",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="協調性",
                    ),
                ),
                (
                    "diligence",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="勤勉性",
                    ),
                ),
                (
                    "humanity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="人間性",
                    ),
                ),
                (
                    "utility_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="日当換算での価値",
                        null=True,
                        verbose_name="有用性(金額評価)",
                    ),
                ),
                (
                    "utility_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="有用性スコア",
                    ),
                ),
                (
                    "working_hours",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="作業時間",
                    ),
                ),
                (
                    "reward",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="報酬",
                    ),
                ),
                (
                    "job_content",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="仕事内容",
                    ),
                ),
                (
                    "preparation",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="段取り",
                    ),
                ),
                (
                    "credibility",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="信用性",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="評価日時"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="jobs.job",
                        verbose_name="対象案件",
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被評価者",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
            ],
        ),
    ]
