# Generated by Django 6.0 on 2026-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_category_alter_job_prefecture_review"),
    ]

    ooperations = [
         #migrations.AddField(
            #model_name='job',
             #name='category',
     #),
        
        migrations.AlterField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
    ]
