# Generated by Django 6.0 on 2026-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_category_alter_job_prefecture_review"),
    ]

    ooperations = [
        # ▼ すでにDBにあるのでコメントアウトしてスキップさせる
        # migrations.AddField(
        #     model_name='job',
        #     name='category',
        #     field=models.CharField(choices=[('general', '多能工・手元')...], default='general', max_length=50, verbose_name='業種・職種'),
        # ),
        
        # ▼ 他の変更（notesなど）はそのまま生かしておく
        migrations.AlterField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
    ]
