# Generated by Django 6.0 on 2026-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_category_alter_job_notes"),
    ]

    operations = [
        #migrations.AddField(
            #model_name="job",
            #name="category",
            #field=models.CharField(
                #choices=[
                    #("general", "多能工・手元"),
                    #("electric", "電気・通信"),
                    #("plumbing", "設備・水道"),
                    #("interior", "内装・クロス・床"),
                    #("exterior", "外装・塗装・防水"),
                    #("scaffold", "足場・鳶・土工"),
                    #("hvac", "空調・ダクト"),
                    #("cleaning", "クリーニング・雑工"),
                    #("other", "その他"),
                #],
                #default="general",
                #max_length=50,
                #verbose_name="業種・職種",
            #),
        #),
        migrations.AlterField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
    ]
