# Generated by Django 6.0 on 2026-02-08 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_category_alter_job_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "多能工・手元"),
                    ("carpenter", "大工（造作・建具）"),
                    ("formwork", "型枠大工・鉄筋工"),
                    ("plasterer", "左官・タイル"),
                    ("sheet_metal", "板金・外壁・屋根"),
                    ("lgs", "軽天・ボード貼り"),
                    ("electric", "電気工・通信・消防"),
                    ("plumbing", "配管工・設備・水道"),
                    ("hvac", "空調・ダクト"),
                    ("interior", "内装（クロス・床）"),
                    ("painting", "塗装・防水"),
                    ("scaffold", "鳶・足場"),
                    ("cleaning", "美装"),
                    ("supervisor", "現場監督・現場代理人"),
                    ("other", "その他"),
                ],
                default="general",
                max_length=50,
                verbose_name="業種・職種",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "選考中"),
                    ("accepted", "採用(契約待ち)"),
                    ("contracted", "契約成立"),
                    ("completed", "業務完了"),
                    ("reviewed", "評価済み"),
                    ("rejected", "不採用"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="utility_amount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="有用性(金額)"
            ),
        ),
    ]
