# Generated by Django 6.0 on 2026-02-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='お知らせ', max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '審査中'), ('accepted', '交渉中（チャットへ）'), ('contracted', '契約成立'), ('completed', '業務完了'), ('canceled', '辞退'), ('rejected', '見送り（また今度お願いします）')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読フラグ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='リンク先URL（任意）'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='受信者'),
        ),
    ]
