# Generated by Django 6.0 on 2026-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_notification_options_notification_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='リンク先URL（任意）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '全ユーザーへの一斉お知らせ',
                'verbose_name_plural': '全ユーザーへの一斉お知らせ',
            },
        ),
    ]
