# Generated by Django 6.0 on 2026-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_broadcast"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("info", "お知らせ"),
                            ("update", "アップデート"),
                            ("maintenance", "メンテナンス"),
                            ("campaign", "キャンペーン"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="カテゴリー",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開する"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "お知らせ",
                "verbose_name_plural": "お知らせ一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
