# Generated by Django 6.0 on 2026-03-04 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='スカウトメッセージ')),
                ('status', models.CharField(choices=[('pending', '返答待ち'), ('accepted', '承諾（チャットへ）'), ('declined', '辞退')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts_sent', to=settings.AUTH_USER_MODEL, verbose_name='スカウトした人（雇い主）')),
                ('target_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='jobs.job', verbose_name='誘いたい表案件')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts_received', to=settings.AUTH_USER_MODEL, verbose_name='スカウトされた人（ワーカー）')),
            ],
        ),
        migrations.CreateModel(
            name='UraProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='裏案件を公開する（ON/OFF）')),
                ('main_occupation', models.CharField(help_text='例: 電気工', max_length=50, verbose_name='職種（メイン）')),
                ('sub_occupations', models.CharField(blank=True, help_text='例: 空調・手元', max_length=100, null=True, verbose_name='職種（サブ2種まで）')),
                ('base_location', models.CharField(help_text='例: 徳島県徳島市', max_length=50, verbose_name='主な活動拠点')),
                ('experience_years', models.CharField(help_text='例: 25年', max_length=20, verbose_name='経験年数')),
                ('good_at', models.TextField(blank=True, help_text='例: 木造建築物', null=True, verbose_name='得意な工事（現場）')),
                ('bad_at', models.TextField(blank=True, help_text='例: 汚水、浄化槽', null=True, verbose_name='不得手な工事（現場）')),
                ('desired_daily_wage', models.CharField(help_text='例: 20,000円+交通費', max_length=50, verbose_name='希望する日当額')),
                ('self_introduction', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ura_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('available', '◎ 空き'), ('negotiable', '△ 要相談'), ('unavailable', '× 不可')], default='available', max_length=20, verbose_name='ステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
