# Generated by Django 6.0 on 2026-03-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_scout_uraprofile_workeravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('job_contracted', '案件契約成立'), ('job_completed', '業務完了報告'), ('scout_accepted', 'スカウト承諾'), ('review_given', '評価を送信'), ('review_received', '評価を受信'), ('other', 'その他（調整など）')], max_length=50, verbose_name='アクション種別')),
                ('points', models.IntegerField(help_text='獲得はプラス、消費はマイナス', verbose_name='増減ポイント')),
                ('description', models.CharField(help_text='例: 案件「〇〇」の契約成立', max_length=255, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.application')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epoint_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Eポイント履歴',
                'verbose_name_plural': 'Eポイント履歴一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
