# Generated by Django 6.0 on 2026-05-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_epointhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ブロックするメールアドレス')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ブロックメール',
            },
        ),
    ]
