# Generated by Django 6.0 on 2026-06-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_blockedemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '応募', 'verbose_name_plural': '応募'},
        ),
        migrations.AlterModelOptions(
            name='blockedemail',
            options={'verbose_name': 'ブロックメールアドレス', 'verbose_name_plural': 'ブロックメールアドレス'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'お問い合わせ', 'verbose_name_plural': 'お問い合わせ'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'チャット', 'verbose_name_plural': 'チャット'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '評価', 'verbose_name_plural': '評価'},
        ),
        migrations.AlterModelOptions(
            name='scout',
            options={'verbose_name': 'スカウト', 'verbose_name_plural': 'スカウト'},
        ),
    ]
