# Generated by Django 6.0 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_alter_application_options_alter_blockedemail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epointhistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("job_posted", "案件投稿"),
                    ("job_contracted", "案件契約成立"),
                    ("job_completed", "業務完了報告"),
                    ("scout_accepted", "スカウト承諾"),
                    ("review_given", "評価を送信"),
                    ("review_received", "評価を受信"),
                    ("other", "その他（調整など）"),
                ],
                max_length=50,
                verbose_name="アクション種別",
            ),
        ),
    ]
