# Generated by Django 6.0 on 2025-12-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "プロフィール",
                "verbose_name_plural": "プロフィール一覧",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="自己紹介・実績"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="活動エリア"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
    ]
