# Generated by Django 6.0 on 2026-01-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_options_alter_profile_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="有料会員"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="拠点"
            ),
        ),
        migrations.CreateModel(
            name="FavoriteArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(
                        choices=[
                            ("北海道", "北海道"),
                            ("青森県", "青森県"),
                            ("岩手県", "岩手県"),
                            ("宮城県", "宮城県"),
                            ("秋田県", "秋田県"),
                            ("山形県", "山形県"),
                            ("福島県", "福島県"),
                            ("茨城県", "茨城県"),
                            ("栃木県", "栃木県"),
                            ("群馬県", "群馬県"),
                            ("埼玉県", "埼玉県"),
                            ("千葉県", "千葉県"),
                            ("東京都", "東京都"),
                            ("神奈川県", "神奈川県"),
                            ("新潟県", "新潟県"),
                            ("富山県", "富山県"),
                            ("石川県", "石川県"),
                            ("福井県", "福井県"),
                            ("山梨県", "山梨県"),
                            ("長野県", "長野県"),
                            ("岐阜県", "岐阜県"),
                            ("静岡県", "静岡県"),
                            ("愛知県", "愛知県"),
                            ("三重県", "三重県"),
                            ("滋賀県", "滋賀県"),
                            ("京都府", "京都府"),
                            ("大阪府", "大阪府"),
                            ("兵庫県", "兵庫県"),
                            ("奈良県", "奈良県"),
                            ("和歌山県", "和歌山県"),
                            ("鳥取県", "鳥取県"),
                            ("島根県", "島根県"),
                            ("岡山県", "岡山県"),
                            ("広島県", "広島県"),
                            ("山口県", "山口県"),
                            ("徳島県", "徳島県"),
                            ("香川県", "香川県"),
                            ("愛媛県", "愛媛県"),
                            ("高知県", "高知県"),
                            ("福岡県", "福岡県"),
                            ("佐賀県", "佐賀県"),
                            ("長崎県", "長崎県"),
                            ("熊本県", "熊本県"),
                            ("大分県", "大分県"),
                            ("宮崎県", "宮崎県"),
                            ("鹿児島県", "鹿児島県"),
                            ("沖縄県", "沖縄県"),
                        ],
                        max_length=20,
                        verbose_name="都道府県",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="市区町村"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "お気に入りエリア",
                "verbose_name_plural": "お気に入りエリア一覧",
            },
        ),
    ]
