# Generated by Django 6.0 on 2026-01-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_is_premium_alter_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_card_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="id_cards/", verbose_name="身分証画像"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="本人確認済み"),
        ),
    ]
