# Generated by Django 6.0 on 2026-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_id_card_image_profile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "アイアン（鉄）"),
                    ("bronze", "ブロンズ（銅）"),
                    ("silver", "シルバー（銀）"),
                    ("gold", "ゴールド（金）"),
                    ("platinum", "プラチナ"),
                ],
                default="iron",
                max_length=20,
                verbose_name="会員ランク",
            ),
        ),
    ]
