# Generated by Django 6.0 on 2026-02-02 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_favoritearea_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="アバター画像"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="自己紹介"),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_years",
            field=models.IntegerField(default=0, verbose_name="経験年数"),
        ),
        migrations.AddField(
            model_name="profile",
            name="invoice_num",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="インボイス登録番号"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="役職・部署"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="qualifications",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="保有資格"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="得意な工事・スキル"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="favoritearea",
            name="city",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="favoritearea",
            name="prefecture",
            field=models.CharField(
                choices=[
                    ("北海道", "北海道"),
                    ("青森県", "青森県"),
                    ("岩手県", "岩手県"),
                    ("宮城県", "宮城県"),
                    ("秋田県", "秋田県"),
                    ("山形県", "山形県"),
                    ("福島県", "福島県"),
                    ("茨城県", "茨城県"),
                    ("栃木県", "栃木県"),
                    ("群馬県", "群馬県"),
                    ("埼玉県", "埼玉県"),
                    ("千葉県", "千葉県"),
                    ("東京都", "東京都"),
                    ("神奈川県", "神奈川県"),
                    ("新潟県", "新潟県"),
                    ("富山県", "富山県"),
                    ("石川県", "石川県"),
                    ("福井県", "福井県"),
                    ("山梨県", "山梨県"),
                    ("長野県", "長野県"),
                    ("岐阜県", "岐阜県"),
                    ("静岡県", "静岡県"),
                    ("愛知県", "愛知県"),
                    ("三重県", "三重県"),
                    ("滋賀県", "滋賀県"),
                    ("大阪府", "大阪府"),
                    ("兵庫県", "兵庫県"),
                    ("奈良県", "奈良県"),
                    ("和歌山県", "和歌山県"),
                    ("鳥取県", "鳥取県"),
                    ("島根県", "島根県"),
                    ("岡山県", "岡山県"),
                    ("広島県", "広島県"),
                    ("山口県", "山口県"),
                    ("徳島県", "徳島県"),
                    ("香川県", "香川県"),
                    ("愛媛県", "愛媛県"),
                    ("高知県", "高知県"),
                    ("福岡県", "福岡県"),
                    ("佐賀県", "佐賀県"),
                    ("長崎県", "長崎県"),
                    ("熊本県", "熊本県"),
                    ("大分県", "大分県"),
                    ("宮崎県", "宮崎県"),
                    ("鹿児島県", "鹿児島県"),
                    ("沖縄県", "沖縄県"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="屋号・会社名"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="id_cards/",
                verbose_name="本人確認書類",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="旧プロフィール画像",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="本人確認済み"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("北海道", "北海道"),
                    ("青森県", "青森県"),
                    ("岩手県", "岩手県"),
                    ("宮城県", "宮城県"),
                    ("秋田県", "秋田県"),
                    ("山形県", "山形県"),
                    ("福島県", "福島県"),
                    ("茨城県", "茨城県"),
                    ("栃木県", "栃木県"),
                    ("群馬県", "群馬県"),
                    ("埼玉県", "埼玉県"),
                    ("千葉県", "千葉県"),
                    ("東京都", "東京都"),
                    ("神奈川県", "神奈川県"),
                    ("新潟県", "新潟県"),
                    ("富山県", "富山県"),
                    ("石川県", "石川県"),
                    ("福井県", "福井県"),
                    ("山梨県", "山梨県"),
                    ("長野県", "長野県"),
                    ("岐阜県", "岐阜県"),
                    ("静岡県", "静岡県"),
                    ("愛知県", "愛知県"),
                    ("三重県", "三重県"),
                    ("滋賀県", "滋賀県"),
                    ("大阪府", "大阪府"),
                    ("兵庫県", "兵庫県"),
                    ("奈良県", "奈良県"),
                    ("和歌山県", "和歌山県"),
                    ("鳥取県", "鳥取県"),
                    ("島根県", "島根県"),
                    ("岡山県", "岡山県"),
                    ("広島県", "広島県"),
                    ("山口県", "山口県"),
                    ("徳島県", "徳島県"),
                    ("香川県", "香川県"),
                    ("愛媛県", "愛媛県"),
                    ("高知県", "高知県"),
                    ("福岡県", "福岡県"),
                    ("佐賀県", "佐賀県"),
                    ("長崎県", "長崎県"),
                    ("熊本県", "熊本県"),
                    ("大分県", "大分県"),
                    ("宮崎県", "宮崎県"),
                    ("鹿児島県", "鹿児島県"),
                    ("沖縄県", "沖縄県"),
                ],
                max_length=100,
                verbose_name="所在地",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "iron"),
                    ("bronze", "bronze"),
                    ("silver", "silver"),
                    ("gold", "gold"),
                    ("platinum", "platinum"),
                ],
                default="iron",
                max_length=20,
            ),
        ),
    ]
