# Generated by Django 6.0 on 2026-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_profile_description_profile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10s", "10代"),
                    ("20s", "20代"),
                    ("30s", "30代"),
                    ("40s", "40代"),
                    ("50s", "50代"),
                    ("60s", "60代以上"),
                ],
                max_length=5,
                null=True,
                verbose_name="年代",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="職種"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "iron"),
                    ("bronze", "bronze"),
                    ("silver", "SILVER"),
                    ("gold", "GOLD"),
                    ("platinum", "PLATINUM"),
                ],
                default="iron",
                max_length=20,
            ),
        ),
    ]
