# Generated by Django 6.0 on 2026-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_profile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="occupation",
        ),
        migrations.AddField(
            model_name="profile",
            name="occupation_main",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="メイン職種"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="occupation_sub",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="サブ職種"
            ),
        ),
    ]
