# Generated by Django 6.0 on 2026-02-08 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_profile_occupation_profile_occupation_main_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
            ],
            options={
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
