# Generated by Django 4.2 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_occupation_profile_occupation_main_and_more'),
    ]

    operations = [
    ]
    
