# Generated by Django 6.0 on 2026-02-11 06:49

import accounts.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_is_founding_member_report_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_founding_member",
            field=models.BooleanField(default=False, verbose_name="創設メンバー"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=accounts.storage_backends.PrivateS3Storage(),
                upload_to="id_cards/",
                verbose_name="本人確認書類",
            ),
        ),
    ]
