# Generated by Django 6.0 on 2026-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_founding_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='LINE ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='担当者名（本名）'),
        ),
    ]
