# Generated by Django 6.0 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_points',
            field=models.IntegerField(default=0, verbose_name='保有Eポイント'),
        ),
    ]
