# Generated by Django 6.0 on 2026-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_e_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所詳細'),
        ),
    ]
