# Generated by Django 6.0 on 2026-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_address_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_rankup_used',
            field=models.BooleanField(default=False, verbose_name='無料ランクアップ使用済み'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='無料ランクの有効期限'),
        ),
    ]
