# Generated by Django 6.0 on 2026-06-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_free_rankup_used_profile_rank_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'ブロック', 'verbose_name_plural': 'ブロック'},
        ),
        migrations.AlterModelOptions(
            name='favoritearea',
            options={'verbose_name': 'お気に入りエリア', 'verbose_name_plural': 'お気に入りエリア'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '通報記録', 'verbose_name_plural': '通報記録'},
        ),
    ]
